baseURL = "https://nir.galon.io/"
languageCode = "en-us"
title = "Nir Galon Resume"
theme = "devRes"

[params]
  description = "Nir Galon resume"
  author = "nirgn975"

  [params.light]
    background = "#E0E0E0"
    text = "#333333"
    textHover = "#0a62b9"
    border = "#999999"
    headerBackground = "#ffffff"

  [params.dark]
    background = "#303030"
    text = "#B3B3B3"
    textHover = "#0a62b9"
    border = "#666666"
    headerBackground = "#424242"

  [params.analytics]
    [params.analytics.plausible]
      enable = true
      domain = "nir.galon.io"
    [params.analytics.google]
      enable = false
      id = "UA-xxxxxxxx-1"
